services:
  app:
    # O build será definido mais tarde com o Dockerfile da aplicação Go
    # Por enquanto, vamos focar no DB
    container_name: ${APP_NAME}-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile # Usaremos um Dockerfile separado para desenvolvimento com live-reload (Air)
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    environment:
      # Variáveis de ambiente da Aplicação
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      # Variáveis de ambiente do Banco de Dados
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: disable
      # Variáveis de ambiente do Redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
  db:
    container_name: ${APP_NAME}-db
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: ${APP_NAME}-redis
    image: redis:8.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: